name: Invite me
description: I would like to be part of the awesome community
title: "Please invite me to the Google Developer Student Club IET DAVV"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Why whould to join GDSC IET-DAVV
      description: What do you like about this community?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our community Page [here](https://gdsc.community.dev/institute-of-engineering-and-technology-davv-indore/)
        Feel free to check out other cool repositories of the GDSC IET-DAVV Community [here](https://github.com/GDSC-IETDAVV)
